# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carlos aka Kiko - Product Designer
email: carlosjgsousa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Carlos aka Kiko is a product designer with over 9 years of experience who solves challenges through design thinking.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nameiskiko.com" # the base hostname & protocol for your site
twitter_username: nameiskiko
github_username:  carlosjgsousa

permalink: /:categories/:title:output_ext

# Build settings
markdown: kramdown
include: ['images']

host: 0.0.0.0

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
  - .jekyll-cache
  - vendor
